[[redirects]]
  force = true
  from = "/api/*"
  status = 200
  to = "https://kynet-server-production.up.railway.app/api/"
[[redirects]]
  force = true
  from = "/auth/*"
  status = 200
  to = "https://kynet-server-production.up.railway.app/auth/"  
[[redirects]]
  from = "/*"
  status = 200
  to = "/index.html"