version: '3.8'
services:
  kynet-server:
    image: "kynet_server"
    container_name: "kynet_server"
    build: 
      context: ./server
    depends_on:
      - mongodb
    volumes:
      - ./server:/server
    ports:
      - "3000:3000"
    networks:
      kynet_net:
        ipv4_address: 172.20.0.2
  kynet-client:
    image: "kynet_client"
    container_name: "kynet_client"
    build: 
      context: ./client
    volumes:
      - ./client:/client
    ports:
      - "3001:3001"
    networks:
      kynet_net:
        ipv4_address: 172.20.0.3
  mongodb:
    image: "mongo:latest"
    container_name: "kynet_database"
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: kynet
    ports:
      - "27017:27017"
    volumes:
      - mongodb:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      kynet_net:
        ipv4_address: 172.20.0.4
networks:
  kynet_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16
          gateway: 172.20.0.1            
volumes:
  mongodb:
    